name: Lead Time

on:
  push:
    branches:
      - main

jobs:
  lead-time:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Find Lead Time
        id: lead-time
        uses: d-kanai/lead-time-action@main
        env:
          PERSONAL_ACCESS_TOKEN_FOR_GITHUB_API: ${{secrets.PERSONAL_ACCESS_TOKEN_FOR_GITHUB_API}}
          RELEASE_BRANCH_NAME: main
          REPOSITORY_NAME: ${{github.repository}}

      - name: Show lead-time output
        run: echo "${{ steps.lead-time.outputs.lead-time }}"
