name: JS Actions

on:
  push:
    branches:
      - main

jobs:
  action:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Find Lead Time
        id: lead-time
        uses: ./.github/actions/lead-time-action
      - name: show
        run: echo "${{ steps.lead-time.outputs.lead-time }}"
