name: Lead Time

on:
  push:
    branches:
      - develop

jobs:
  lead-time:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Find Lead Time
        id: lead-time
        uses: d-kanai/lead-time-action@develop
        env:
          PERSONAL_ACCESS_TOKEN_FOR_GITHUB_API: ${{secrets.PERSONAL_ACCESS_TOKEN_FOR_GITHUB_API}}
          REPOSITORY_NAME: ${{github.repository}}
          ENABLE_SAVE_HISTORY_FILE: true
          GITHUB_USER: d-kanai
          RELEASE_BRANCH_NAME: main
          SAVE_HISTORY_FILE_BRANCH: simple-lead-time-action

      - name: Show lead-time output
        run: echo "${{ steps.lead-time.outputs.lead-time }}"

      - name: Show history-link output
        run: echo "${{ steps.lead-time.outputs.history-link }}"
