name: Lead Time

on:
  push:
    branches:
      - main

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Find Lead Time
        id: lead-time
        uses: ./.github/actions/lead-time-action
        env:
          PERSONAL_ACCESS_TOKEN_FOR_GITHUB_API: ${{secrets.PERSONAL_ACCESS_TOKEN_FOR_GITHUB_API}}
      - name: show
        run: echo "${{ steps.lead-time.outputs.lead-time }}"
